import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/Header/Header";
import ReduxProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });
import styles from "./Layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className={styles.layout}>
            <Header />
            <main className={styles.main}>
              {children}
            </main>
          </div >
        </ReduxProvider>
      </body>
    </html >
  );
}
